"""
Mixin providing latent-space methods for RealGenerator.

Methods: get_latest_embeddings, get_training_history, get_synthesizer_model,
         get_encoder, get_decoder, encode_to_latent, decode_from_latent,
         to_anndata, apply_latent_differentiation.
"""

import warnings
from typing import Any, List, Optional

import numpy as np
import pandas as pd
import torch


class _LatentMixin:

    def get_latest_embeddings(self) -> Optional[np.ndarray]:
        """
        Returns the latest latent embeddings generated by methods supporting
        latent space differentiation (e.g., tvae, ctgan, scvi). Returns None if
        no embeddings were saved.
        """
        return getattr(self, "latest_embeddings", None)

    def get_training_history(self) -> Optional[dict]:
        """
        Returns the training history dict from the last run, if available.
        For scVI/scANVI: contains metrics like 'train_loss_epoch', 'elbo_train',
        'reconstruction_loss_train', 'kl_local_train'.
        Returns None if not available (e.g., non-scVI models).
        """
        return getattr(self, "training_history", None)

    def get_synthesizer_model(self) -> Any:
        """
        Returns the underlying synthesizer model used for generation.

        For deep-learning methods the returned object is the high-level wrapper
        (e.g. Synthcity plugin, scvi.model.SCVI, GEARS model).  Use
        ``get_encoder`` / ``get_decoder`` to reach the internal networks.

        Returns None if no model has been trained yet.
        """
        return self.synthesizer

    def get_encoder(self) -> Optional[Any]:
        """
        Returns the encoder network of the trained model, if it exists.

        Supported methods and what is returned:
            - tvae / rtvae: the Synthcity PyTorch encoder
            - scvi: ``module.z_encoder`` (or ``module.encoder``)
            - ddpm / timegan / timevae / fflows: the internal encoder if the
              Synthcity plugin exposes one, otherwise None
            - gears: None (GEARS has no explicit encoder/decoder split)
            - gmm / copula / bayesian_network: None (no neural encoder)
            - smote / adasyn / resample / cart / rf / lgbm: None

        Returns:
            The encoder module, or None if not available.
        """
        if not self.synthesizer:
            return None

        if self.method in ("tvae", "rtvae"):
            try:
                return self.synthesizer.model.model.encoder
            except AttributeError:
                return None

        if self.method == "scvi":
            module = getattr(self.synthesizer, "module", None)
            if module is None:
                return None
            return getattr(module, "z_encoder", None) or getattr(module, "encoder", None)

        if self.method in ("ddpm", "timegan", "timevae", "fflows"):
            try:
                return self.synthesizer.model.model.encoder
            except AttributeError:
                return None

        return None

    def get_decoder(self) -> Optional[Any]:
        if not self.synthesizer:
            return None

        if self.method in ("tvae", "rtvae"):
            try:
                return self.synthesizer.model.model.decoder
            except AttributeError:
                return None

        if self.method == "scvi":
            module = getattr(self.synthesizer, "module", None)
            if module is None:
                return None
            return getattr(module, "decoder", None)

        if self.method in ("ddpm", "timegan", "timevae", "fflows"):
            try:
                return self.synthesizer.model.model.decoder
            except AttributeError:
                return None

        return None

    def encode_to_latent(
        self,
        data,
        target_col: Optional[str] = None,
    ) -> "torch.Tensor":
        """
        Encodes ``data`` into the model's latent space, handling the full
        preprocessing pipeline for each supported method.

        - **tvae / rtvae**: runs TabularEncoder → VAE encoder → returns ``mu``
          (mean of the approximate posterior).  The TabularEncoder was fitted
          on the *complete* training DataFrame (including ``target_col``), so
          ``data`` must contain the same columns, in the same order, as the
          training data — ``target_col`` included.
        - **scvi / scanvi**: calls ``model.get_latent_representation()`` and
          returns the result as a float32 tensor.

        Unlike :meth:`get_encoder`, which exposes the raw PyTorch module, this
        method handles the method-specific preprocessing automatically. Use it
        when implementing external drift analyses that need latent
        representations for both TVAE and SCVI without rewriting the encoding
        pipeline each time.

        Parameters
        ----------
        data:
            - TVAE/RTVAE: a :class:`pandas.DataFrame` with **all** columns
              used during training (including ``target_col``).
            - SCVI/SCANVI: a :class:`pandas.DataFrame` *or* an
              ``AnnData`` object whose ``var_names`` match the training genes.
        target_col:
            Label column used to build the optional conditioning tensor for
            TVAE models trained with a conditional dimension.  For SCVI this
            argument is ignored.

        Returns
        -------
        torch.Tensor
            Float32 tensor of shape ``(n_samples, n_latent)``.

        Raises
        ------
        RuntimeError
            If no model has been trained yet, or the method is not supported.
        """
        if not self.synthesizer:
            raise RuntimeError("No trained model found. Call generate() first.")

        if self.method in ("tvae", "rtvae"):
            tabular_model = self.synthesizer.model
            pytorch_model = tabular_model.model
            pytorch_model.eval()

            # TVAE trains the TabularEncoder on the FULL DataFrame (including
            # target_col).  We must pass the same columns here; do not drop
            # target_col before encoding.
            data_encoded = tabular_model.encode(data)
            data_tensor = torch.tensor(
                data_encoded.values, dtype=torch.float32
            ).to(pytorch_model.device)

            # Append conditional dimensions expected by the encoder.
            # n_units_conditional may be non-zero even without explicit cond (Synthcity default).
            # Always append a cond tensor of the right size; use label one-hot when target_col
            # is available, zeros otherwise.
            cond_dim = getattr(pytorch_model, "n_units_conditional", 0)
            if cond_dim > 0:
                if target_col and isinstance(data, pd.DataFrame) and target_col in data.columns:
                    cond_tensor = self._build_cond_tensor(
                        data, target_col, cond_dim, pytorch_model.device
                    )
                else:
                    cond_tensor = torch.zeros(len(data_tensor), cond_dim, device=pytorch_model.device)
                data_tensor = torch.cat([data_tensor, cond_tensor], dim=1)

            with torch.no_grad():
                encoder_out = pytorch_model.encoder(data_tensor)
                mu = encoder_out[0] if isinstance(encoder_out, (tuple, list)) else encoder_out
            return mu

        if self.method in ("scvi", "scanvi"):
            model = self.synthesizer
            z = model.get_latent_representation()
            return torch.tensor(z, dtype=torch.float32)

        raise RuntimeError(
            f"encode_to_latent() is not supported for method '{self.method}'. "
            "Supported: tvae, rtvae, scvi, scanvi."
        )

    def decode_from_latent(
        self,
        z: "torch.Tensor",
        data=None,
        target_col: Optional[str] = None,
    ) -> pd.DataFrame:
        """
        Decodes latent vectors ``z`` back to the original feature space.

        - **tvae / rtvae**: runs VAE decoder → TabularEncoder inverse_transform.
        - **scvi / scanvi**: calls the model's generative pass and returns
          a DataFrame with the original gene columns.

        Parameters
        ----------
        z:
            Float32 tensor of shape ``(n_samples, n_latent)`` produced by
            :meth:`encode_to_latent` (or a manually perturbed version of it).
        data:
            Reference data used to infer library size (SCVI only) and column
            names.  Can be a :class:`pandas.DataFrame` or ``AnnData``.
        target_col:
            Label column to attach to the output DataFrame.  When provided
            together with ``data``, labels are copied from the reference.

        Returns
        -------
        pandas.DataFrame
            Decoded samples in the original feature space.

        Raises
        ------
        RuntimeError
            If no model has been trained yet, or the method is not supported.
        """
        if not self.synthesizer:
            raise RuntimeError("No trained model found. Call generate() first.")

        n_samples = z.shape[0]

        if self.method in ("tvae", "rtvae"):
            tabular_model = self.synthesizer.model
            pytorch_model = tabular_model.model
            pytorch_model.eval()

            cond_dim = getattr(pytorch_model, "n_units_conditional", 0)
            cond_tensor = None
            if cond_dim > 0:
                if target_col is not None and data is not None and isinstance(data, pd.DataFrame) and target_col in data.columns:
                    cond_tensor = self._build_cond_tensor(
                        data, target_col, cond_dim, pytorch_model.device
                    )
                else:
                    cond_tensor = torch.zeros(n_samples, cond_dim, device=pytorch_model.device)

            z = z.to(pytorch_model.device)
            with torch.no_grad():
                reconstructed = pytorch_model.decoder(z, cond_tensor)

            # Get encoded column names: encode the full data (TabularEncoder
            # was fitted on the complete DataFrame including target_col).
            enc_cols = tabular_model.encode(data).columns if data is not None else None
            reconstructed_df = pd.DataFrame(
                reconstructed.cpu().numpy(),
                columns=enc_cols,
            )
            synth_df = tabular_model.decode(reconstructed_df)
            return synth_df

        if self.method in ("scvi", "scanvi"):
            model = self.synthesizer
            device = model.device if hasattr(model, "device") else next(model.module.parameters()).device

            if data is not None and hasattr(data, "X"):
                raw = self._safe_to_dense(data.X)
                orig_log_lib = np.log(raw.sum(axis=1) + 1e-8)
            elif data is not None and isinstance(data, pd.DataFrame):
                num_cols = data.select_dtypes(include=[np.number]).columns
                if target_col:
                    num_cols = [c for c in num_cols if c != target_col]
                orig_log_lib = np.log(data[num_cols].values.sum(axis=1) + 1e-8)
            else:
                orig_log_lib = np.zeros(n_samples)

            z = z.to(device)
            library_tensor = torch.tensor(
                orig_log_lib, dtype=torch.float32
            ).unsqueeze(1).to(device)
            batch_index = torch.zeros(n_samples, 1, dtype=torch.long).to(device)

            y_tensor = None
            if getattr(model.module, "dispersion", "gene") == "gene-label" and data is not None:
                try:
                    label_registry = model.adata_manager.get_state_registry("labels")
                    cat_mapping = label_registry.categorical_mapping
                    label_map = {str(cat): i for i, cat in enumerate(cat_mapping)}
                    if hasattr(data, "obs") and target_col in data.obs.columns:
                        labels = data.obs[target_col].astype(str).values
                    elif isinstance(data, pd.DataFrame) and target_col in data.columns:
                        labels = data[target_col].astype(str).values
                    else:
                        labels = None
                    if labels is not None:
                        y_tensor = torch.tensor(
                            [label_map.get(l, 0) for l in labels],
                            dtype=torch.long,
                        ).unsqueeze(1).to(device)
                except Exception:
                    pass

            with torch.no_grad():
                gen_out = model.module.generative(
                    z=z,
                    library=library_tensor,
                    batch_index=batch_index,
                    y=y_tensor,
                )
                px_dist = gen_out["px"]
                vals = (
                    px_dist.sample().cpu().numpy()
                    if hasattr(px_dist, "sample")
                    else px_dist.mean.cpu().numpy()
                )

            col_names = (
                data.var_names.tolist()
                if hasattr(data, "var_names")
                else [c for c in (data.columns if isinstance(data, pd.DataFrame) else []) if c != target_col]
            )
            synth_df = pd.DataFrame(vals, columns=col_names)
            if target_col is not None and data is not None:
                if hasattr(data, "obs") and target_col in data.obs.columns:
                    synth_df[target_col] = data.obs[target_col].values[:n_samples]
                elif isinstance(data, pd.DataFrame) and target_col in data.columns:
                    synth_df[target_col] = data[target_col].values[:n_samples]
            return synth_df

        raise RuntimeError(
            f"decode_from_latent() is not supported for method '{self.method}'. "
            "Supported: tvae, rtvae, scvi, scanvi."
        )

    @staticmethod
    def to_anndata(
        df: pd.DataFrame,
        target_col: Optional[str] = None,
        obs_cols: Optional[List[str]] = None
    ):
        """
        Converts a generated synthetic DataFrame back to an AnnData object.

        Args:
            df (pd.DataFrame): The synthetic data.
            target_col (str): Column to use as 'cell_type' in adata.obs.
            obs_cols (list): Additional columns to move from features (X) to metadata (obs).

        Returns:
            anndata.AnnData: The data in single-cell format.
        """
        try:
            import anndata as ad
        except ImportError:
            raise ImportError("anndata is required. Please install it with 'pip install anndata'")

        obs_cols = obs_cols or []
        if target_col and target_col not in obs_cols:
            obs_cols.append(target_col)

        # Filter existing obs_cols
        obs_cols = [c for c in obs_cols if c in df.columns]

        # Features (X)
        x_cols = [c for c in df.columns if c not in obs_cols]

        # Numeric only for X usually
        numeric_x = df[x_cols].select_dtypes(include=[np.number])
        if len(numeric_x.columns) < len(x_cols):
             warnings.warn(f"Dropping non-numeric columns from X: {set(x_cols) - set(numeric_x.columns)}")

        adata = ad.AnnData(X=numeric_x.values.astype(np.float32))
        adata.var_names = numeric_x.columns.tolist()
        adata.obs_names = [f"cell_{i}" for i in range(len(df))]

        if obs_cols:
            adata.obs = df[obs_cols].copy()
            if target_col and target_col in adata.obs.columns:
                adata.obs["cell_type"] = adata.obs[target_col].astype(str)

        return adata

    def apply_latent_differentiation(
        self,
        syn: Any,
        data: pd.DataFrame,
        n_samples: int,
        target_col: str,
        differentiation_factor: float,
        method: str,
        **kwargs
    ) -> pd.DataFrame:
        """
        Unified implementation of latent space differentiation for TVAE and scVI.

        Follows a 5-step process:
        1. Generate latent space z(d) for samples.
        2. Calculate centers of mass (centroids) for cases (cmca) and controls (cmco).
        3. Calculate distance vector c = cmca - cmco (for case) or c = cmco - cmca (for control).
        4. Generate synthetic latent z'(d) = z(d) + a * c.
        5. Decode z'(d) and apply flexible clipping.
        """
        self.logger.info(f"Applying unified latent differentiation for {method} (factor: {differentiation_factor})")

        clipping_mode = kwargs.get("clipping_mode", "strict")
        clipping_factor = kwargs.get("clipping_factor", None)
        clip_min = kwargs.get("clip_min", None)
        clip_max = kwargs.get("clip_max", None)

        try:
            # Step 1: Generate Latent Space z(d)
            if method == "tvae":
                tabular_model = syn.model
                pytorch_model = tabular_model.model
                pytorch_model.eval()

                orig_target_dtype = data[target_col].dtype
                data_for_encode = data.copy()
                data_for_encode[target_col] = data_for_encode[target_col].astype(str)
                data_encoded = tabular_model.encode(data_for_encode)
                data_tensor = torch.tensor(data_encoded.values, dtype=torch.float32).to(pytorch_model.device)

                target_series = data[target_col]
                unique_classes = target_series.unique()
                if len(unique_classes) != 2:
                    self.logger.warning(f"Differentiation works best with 2 classes, found {len(unique_classes)}. Using first two.")

                control_val = unique_classes[0]
                case_val = unique_classes[1]

                # The TVAE encoder was trained on encoded features + conditioning dims.
                # If the model has conditional dimensions, we must append them
                # so the input size matches what the encoder expects.
                cond_dim = getattr(pytorch_model, "n_units_conditional", 0)
                with torch.no_grad():
                    cond_tensor_enc = None
                    if cond_dim > 0:
                        label_to_idx = {str(control_val): 0, str(case_val): 1}
                        labels_enc = target_series.values
                        label_indices = torch.tensor(
                            [label_to_idx.get(str(l), 0) for l in labels_enc],
                            dtype=torch.long,
                            device=pytorch_model.device,
                        )
                        cond_tensor_enc = torch.zeros(
                            len(labels_enc), cond_dim, device=pytorch_model.device
                        )
                        cond_tensor_enc.scatter_(1, label_indices.unsqueeze(1).clamp(max=cond_dim - 1), 1.0)
                        data_tensor = torch.cat([data_tensor, cond_tensor_enc], dim=1)

                    encoder_out = pytorch_model.encoder(data_tensor)
                    mu = encoder_out[0] if isinstance(encoder_out, (tuple, list)) else encoder_out
                    z = mu

            elif method == "scvi":
                model = syn
                device = model.device if hasattr(model, "device") else model.module.device
                z = torch.tensor(model.get_latent_representation(), dtype=torch.float32).to(device)
                # Support both AnnData and DataFrame as input
                if hasattr(data, "obs"):
                    unique_classes = data.obs[target_col].unique()
                else:
                    unique_classes = data[target_col].unique()
                control_val = unique_classes[0]
                case_val = unique_classes[1]
            else:
                return syn.generate(count=n_samples, random_state=self.random_state).dataframe()

            # Step 2: Calculate Centroids
            if method == "scvi" and hasattr(data, "obs"):
                labels = data.obs[target_col].astype(str).values
                mask_case = labels == str(case_val)
                mask_control = labels == str(control_val)
            elif method == "scvi":
                labels = data[target_col].astype(str).values
                mask_case = labels == str(case_val)
                mask_control = labels == str(control_val)
            else:
                labels = data[target_col].values
                mask_case = labels == case_val
                mask_control = labels == control_val

            self.logger.debug(
                f"[Differentiation] unique_classes={unique_classes}, "
                f"case_val={case_val!r} ({type(case_val).__name__}), "
                f"control_val={control_val!r} ({type(control_val).__name__}), "
                f"labels sample={labels[:5]}, mask_case sum={mask_case.sum()}, mask_control sum={mask_control.sum()}"
            )

            if mask_case.sum() == 0 or mask_control.sum() == 0:
                raise ValueError(
                    f"Empty mask for differentiation: mask_case={mask_case.sum()}, "
                    f"mask_control={mask_control.sum()}. "
                    f"unique_classes={unique_classes}, labels sample={labels[:5]}"
                )

            cmca = z[mask_case].mean(dim=0)
            cmco = z[mask_control].mean(dim=0)

            if torch.isnan(cmca).any() or torch.isnan(cmco).any():
                raise ValueError("Centroid calculation returned NaNs after masking.")

            # Step 3: Calculate distance vector
            distance_vector_case = cmca - cmco       # direction to push case samples
            distance_vector_control = cmco - cmca    # direction to push control samples

            self.logger.info(f"[Differentiation] Centroid '{case_val}' (case):    {cmca.cpu().numpy().round(4)}")
            self.logger.info(f"[Differentiation] Centroid '{control_val}' (control): {cmco.cpu().numpy().round(4)}")
            self.logger.info(f"[Differentiation] Distance vector (case→control):  {distance_vector_case.cpu().numpy().round(4)}")
            self.logger.info(f"[Differentiation] ||distance||: {torch.norm(distance_vector_case).item():.4f}")
            self.logger.info(f"[Differentiation] Shift applied: factor={differentiation_factor} × ||d||={torch.norm(distance_vector_case).item():.4f} = {differentiation_factor * torch.norm(distance_vector_case).item():.4f}")

            # Step 4: Enhance Latent Space — push classes apart
            z_prime = z.clone()
            z_prime[mask_case] += differentiation_factor * distance_vector_case
            z_prime[mask_control] += differentiation_factor * distance_vector_control

            cmca_prime = z_prime[mask_case].mean(dim=0)
            cmco_prime = z_prime[mask_control].mean(dim=0)
            self.logger.info(f"[Differentiation] New centroid '{case_val}':    {cmca_prime.cpu().numpy().round(4)}")
            self.logger.info(f"[Differentiation] New centroid '{control_val}': {cmco_prime.cpu().numpy().round(4)}")
            self.logger.info(f"[Differentiation] New ||distance||: {torch.norm(cmca_prime - cmco_prime).item():.4f}")

            # Step 5: Decode
            if method == "tvae":
                with torch.no_grad():

                    # Synthcity's Decoder.forward(X, cond) expects latent and
                    # conditioning SEPARATELY — it concatenates them internally.
                    # n_units_conditional lives on the VAE (pytorch_model), not on the Decoder.
                    cond_dim = getattr(pytorch_model, "n_units_conditional", 0)

                    cond_tensor = None
                    if cond_dim > 0:
                        label_to_idx = {str(control_val): 0, str(case_val): 1}
                        label_indices = torch.tensor(
                            [label_to_idx.get(str(l), 0) for l in labels],
                            dtype=torch.long,
                            device=pytorch_model.device,
                        )
                        cond_tensor = torch.zeros(
                            len(labels), cond_dim, device=pytorch_model.device
                        )
                        cond_tensor.scatter_(1, label_indices.unsqueeze(1).clamp(max=cond_dim - 1), 1.0)

                    reconstructed_tensor = pytorch_model.decoder(z_prime, cond_tensor)

                reconstructed_df = pd.DataFrame(
                    reconstructed_tensor.cpu().numpy(),
                    columns=data_encoded.columns
                )
                synth_df = syn.model.decode(reconstructed_df)
                synth_df[target_col] = data[target_col].values
                try:
                    synth_df[target_col] = synth_df[target_col].astype(orig_target_dtype)
                except (ValueError, TypeError):
                    pass

            elif method == "scvi":
                with torch.no_grad():
                    # Preserve library size logic
                    if hasattr(data, "X"):
                        orig_lib_size = self._safe_to_dense(data.X).sum(axis=1)
                        orig_log_lib = np.log(orig_lib_size + 1e-8)
                    else:
                        orig_log_lib = np.zeros(len(data))

                    library_tensor = torch.tensor(orig_log_lib, dtype=torch.float32).unsqueeze(1).to(model.device)
                    batch_index = torch.zeros(len(z), 1, dtype=torch.long).to(model.device)

                    y_tensor = None
                    if getattr(model.module, "dispersion", "gene") == "gene-label":
                        label_registry = model.adata_manager.get_state_registry("labels")
                        cat_mapping = label_registry.categorical_mapping
                        label_map = {str(cat): i for i, cat in enumerate(cat_mapping)}
                        y_tensor = torch.tensor(
                            [label_map[str(m)] for m in labels],
                            dtype=torch.long
                        ).unsqueeze(1).to(model.device)

                    gen_outputs = model.module.generative(
                        z=z_prime,
                        library=library_tensor,
                        batch_index=batch_index,
                        y=y_tensor,
                    )
                    px_dist = gen_outputs["px"]
                    synth_values = px_dist.sample().cpu().numpy() if hasattr(px_dist, "sample") else px_dist.mean.cpu().numpy()

                # Use var_names from adata if possible, or columns from data
                col_names = data.var_names if hasattr(data, "var_names") else [c for c in data.columns if c != target_col]
                synth_df = pd.DataFrame(synth_values, columns=col_names)
                synth_df[target_col] = labels

            # Sample/Match size
            if len(synth_df) != n_samples:
                synth_df = synth_df.sample(
                    n=n_samples,
                    replace=(n_samples > len(synth_df)),
                    random_state=self.random_state
                ).reset_index(drop=True)

            # Clipping and Integer Preservation
            numeric_cols = synth_df.select_dtypes(include=[np.number]).columns
            # Resolve column access for both DataFrame and AnnData
            data_columns = data.var_names if hasattr(data, "var_names") else data.columns
            for col in numeric_cols:
                if col in data_columns:
                    col_data = data[:, col].X if hasattr(data, "var_names") else data[col]
                    if hasattr(col_data, "toarray"):
                        col_data = col_data.toarray().ravel()
                    elif hasattr(col_data, "A1"):
                        col_data = col_data.A1
                    col_series = pd.Series(col_data).dropna()
                    orig_min = col_series.min()
                    orig_max = col_series.max()

                    if clipping_mode == "none":
                        # No clipping, only preserve integer dtype
                        if pd.api.types.is_integer_dtype(col_series):
                            synth_df[col] = synth_df[col].round().astype(int)
                        continue

                    col_clip_min = clip_min.get(col) if isinstance(clip_min, dict) else clip_min
                    col_clip_max = clip_max.get(col) if isinstance(clip_max, dict) else clip_max

                    if col_clip_min is None and col_clip_max is None:
                        if clipping_mode == "permissive" and clipping_factor is not None:
                            col_range = orig_max - orig_min
                            low = orig_min - (clipping_factor * col_range)
                            high = orig_max + (clipping_factor * col_range)
                        else:  # strict: original range
                            low, high = orig_min, orig_max
                        col_clip_min, col_clip_max = low, high

                    synth_df[col] = synth_df[col].clip(lower=col_clip_min, upper=col_clip_max)

                    if pd.api.types.is_integer_dtype(col_series):
                        synth_df[col] = synth_df[col].round().astype(int)

            return synth_df

        except ValueError:
            raise
        except Exception as e:
            self.logger.error(f"Unified differentiation failed for {method}: {e}. Falling back to standard generation.")
            if method == "scvi":
                # Fallback: sample from prior without differentiation
                self.logger.warning("scVI fallback: generating from standard latent prior (no differentiation).")
                import scvi as _scvi_mod  # noqa: F401
                n_latent = syn.module.n_latent
                rng = np.random.default_rng(self.random_state)
                latent_samples = rng.standard_normal((n_samples, n_latent)).astype(np.float32)
                latent_tensor = torch.tensor(latent_samples).to(syn.device)
                mean_lib = float(np.log(10000))
                library_tensor = torch.full((n_samples, 1), mean_lib, dtype=torch.float32).to(syn.device)
                batch_index = torch.zeros(n_samples, 1, dtype=torch.long).to(syn.device)
                with torch.no_grad():
                    y_fallback = None
                    if getattr(syn.module, "dispersion", "gene") == "gene-label":
                        y_fallback = torch.zeros(n_samples, 1, dtype=torch.long).to(syn.device)
                    gen_out = syn.module.generative(z=latent_tensor, library=library_tensor, batch_index=batch_index, y=y_fallback)
                    px_dist = gen_out["px"]
                    vals = px_dist.sample().cpu().numpy() if hasattr(px_dist, "sample") else px_dist.mean.cpu().numpy()
                col_names = syn.adata.var_names.tolist()
                return pd.DataFrame(vals, columns=col_names)
            return syn.generate(count=n_samples, random_state=self.random_state).dataframe()
